


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."league" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "description" character varying
);


ALTER TABLE "public"."league" OWNER TO "postgres";


ALTER TABLE "public"."league" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."League_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."team" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "league_id" bigint NOT NULL,
    "name" "text" NOT NULL
);


ALTER TABLE "public"."team" OWNER TO "postgres";


ALTER TABLE "public"."team" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Team_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."game_response" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "game_team_id" bigint,
    "attending" boolean DEFAULT true,
    "bringing_beer" boolean DEFAULT false,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "team_member_id" bigint
);


ALTER TABLE "public"."game_response" OWNER TO "postgres";


ALTER TABLE "public"."game_response" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."game_response_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."game_teams" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "game_id" bigint,
    "team_id" bigint,
    "is_home" boolean
);


ALTER TABLE "public"."game_teams" OWNER TO "postgres";


ALTER TABLE "public"."game_teams" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."game_teams_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."games" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "season_id" bigint,
    "game_time" timestamp with time zone,
    "location" "text"
);


ALTER TABLE "public"."games" OWNER TO "postgres";


ALTER TABLE "public"."games" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."games_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profile" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "display_name" "text"
);


ALTER TABLE "public"."profile" OWNER TO "postgres";


ALTER TABLE "public"."profile" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."profile_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."season" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "league_id" bigint NOT NULL,
    "start_date" "date",
    "end_date" "date",
    "is_active" boolean DEFAULT false
);


ALTER TABLE "public"."season" OWNER TO "postgres";


ALTER TABLE "public"."season" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."season_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."team_member" (
    "id" bigint NOT NULL,
    "joined_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "team_id" bigint,
    "profile_id" bigint,
    "role" "text",
    "position" "text"
);


ALTER TABLE "public"."team_member" OWNER TO "postgres";


ALTER TABLE "public"."team_member" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."team_member_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."league"
    ADD CONSTRAINT "League_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."league"
    ADD CONSTRAINT "League_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."team"
    ADD CONSTRAINT "Team_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."game_response"
    ADD CONSTRAINT "game_response_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."game_teams"
    ADD CONSTRAINT "game_teams_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profile"
    ADD CONSTRAINT "profile_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."season"
    ADD CONSTRAINT "season_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."team_member"
    ADD CONSTRAINT "team_member_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."team"
    ADD CONSTRAINT "Team_league_id_fkey" FOREIGN KEY ("league_id") REFERENCES "public"."league"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."game_response"
    ADD CONSTRAINT "game_response_game_team_id_fkey" FOREIGN KEY ("game_team_id") REFERENCES "public"."game_teams"("id");



ALTER TABLE ONLY "public"."game_response"
    ADD CONSTRAINT "game_response_team_member_id_fkey" FOREIGN KEY ("team_member_id") REFERENCES "public"."team_member"("id");



ALTER TABLE ONLY "public"."game_teams"
    ADD CONSTRAINT "game_teams_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."games"("id");



ALTER TABLE ONLY "public"."game_teams"
    ADD CONSTRAINT "game_teams_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."team"("id");



ALTER TABLE ONLY "public"."games"
    ADD CONSTRAINT "games_season_id_fkey" FOREIGN KEY ("season_id") REFERENCES "public"."season"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."profile"
    ADD CONSTRAINT "profile_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."season"
    ADD CONSTRAINT "season_league_id_fkey" FOREIGN KEY ("league_id") REFERENCES "public"."league"("id");



ALTER TABLE ONLY "public"."team_member"
    ADD CONSTRAINT "team_member_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profile"("id");



ALTER TABLE ONLY "public"."team_member"
    ADD CONSTRAINT "team_member_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "public"."team"("id");



ALTER TABLE "public"."game_response" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."game_teams" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."games" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."league" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profile" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."season" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."team" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."team_member" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";





































































































































































GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."league" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."league" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."league" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."team" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."team" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."team" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."game_response" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."game_response" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."game_response" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."game_teams" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."game_teams" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."game_teams" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."games" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."games" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."games" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."profile" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."profile" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."profile" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."season" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."season" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."season" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."team_member" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."team_member" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."team_member" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "service_role";































drop extension if exists "pg_net";

revoke delete on table "public"."game_response" from "anon";

revoke insert on table "public"."game_response" from "anon";

revoke select on table "public"."game_response" from "anon";

revoke update on table "public"."game_response" from "anon";

revoke delete on table "public"."game_response" from "authenticated";

revoke insert on table "public"."game_response" from "authenticated";

revoke select on table "public"."game_response" from "authenticated";

revoke update on table "public"."game_response" from "authenticated";

revoke delete on table "public"."game_response" from "service_role";

revoke insert on table "public"."game_response" from "service_role";

revoke select on table "public"."game_response" from "service_role";

revoke update on table "public"."game_response" from "service_role";

revoke delete on table "public"."game_teams" from "anon";

revoke insert on table "public"."game_teams" from "anon";

revoke select on table "public"."game_teams" from "anon";

revoke update on table "public"."game_teams" from "anon";

revoke delete on table "public"."game_teams" from "authenticated";

revoke insert on table "public"."game_teams" from "authenticated";

revoke select on table "public"."game_teams" from "authenticated";

revoke update on table "public"."game_teams" from "authenticated";

revoke delete on table "public"."game_teams" from "service_role";

revoke insert on table "public"."game_teams" from "service_role";

revoke select on table "public"."game_teams" from "service_role";

revoke update on table "public"."game_teams" from "service_role";

revoke delete on table "public"."games" from "anon";

revoke insert on table "public"."games" from "anon";

revoke select on table "public"."games" from "anon";

revoke update on table "public"."games" from "anon";

revoke delete on table "public"."games" from "authenticated";

revoke insert on table "public"."games" from "authenticated";

revoke select on table "public"."games" from "authenticated";

revoke update on table "public"."games" from "authenticated";

revoke delete on table "public"."games" from "service_role";

revoke insert on table "public"."games" from "service_role";

revoke select on table "public"."games" from "service_role";

revoke update on table "public"."games" from "service_role";

revoke delete on table "public"."league" from "anon";

revoke insert on table "public"."league" from "anon";

revoke select on table "public"."league" from "anon";

revoke update on table "public"."league" from "anon";

revoke delete on table "public"."league" from "authenticated";

revoke insert on table "public"."league" from "authenticated";

revoke select on table "public"."league" from "authenticated";

revoke update on table "public"."league" from "authenticated";

revoke delete on table "public"."league" from "service_role";

revoke insert on table "public"."league" from "service_role";

revoke select on table "public"."league" from "service_role";

revoke update on table "public"."league" from "service_role";

revoke delete on table "public"."profile" from "anon";

revoke insert on table "public"."profile" from "anon";

revoke select on table "public"."profile" from "anon";

revoke update on table "public"."profile" from "anon";

revoke delete on table "public"."profile" from "authenticated";

revoke insert on table "public"."profile" from "authenticated";

revoke select on table "public"."profile" from "authenticated";

revoke update on table "public"."profile" from "authenticated";

revoke delete on table "public"."profile" from "service_role";

revoke insert on table "public"."profile" from "service_role";

revoke select on table "public"."profile" from "service_role";

revoke update on table "public"."profile" from "service_role";

revoke delete on table "public"."season" from "anon";

revoke insert on table "public"."season" from "anon";

revoke select on table "public"."season" from "anon";

revoke update on table "public"."season" from "anon";

revoke delete on table "public"."season" from "authenticated";

revoke insert on table "public"."season" from "authenticated";

revoke select on table "public"."season" from "authenticated";

revoke update on table "public"."season" from "authenticated";

revoke delete on table "public"."season" from "service_role";

revoke insert on table "public"."season" from "service_role";

revoke select on table "public"."season" from "service_role";

revoke update on table "public"."season" from "service_role";

revoke delete on table "public"."team" from "anon";

revoke insert on table "public"."team" from "anon";

revoke select on table "public"."team" from "anon";

revoke update on table "public"."team" from "anon";

revoke delete on table "public"."team" from "authenticated";

revoke insert on table "public"."team" from "authenticated";

revoke select on table "public"."team" from "authenticated";

revoke update on table "public"."team" from "authenticated";

revoke delete on table "public"."team" from "service_role";

revoke insert on table "public"."team" from "service_role";

revoke select on table "public"."team" from "service_role";

revoke update on table "public"."team" from "service_role";

revoke delete on table "public"."team_member" from "anon";

revoke insert on table "public"."team_member" from "anon";

revoke select on table "public"."team_member" from "anon";

revoke update on table "public"."team_member" from "anon";

revoke delete on table "public"."team_member" from "authenticated";

revoke insert on table "public"."team_member" from "authenticated";

revoke select on table "public"."team_member" from "authenticated";

revoke update on table "public"."team_member" from "authenticated";

revoke delete on table "public"."team_member" from "service_role";

revoke insert on table "public"."team_member" from "service_role";

revoke select on table "public"."team_member" from "service_role";

revoke update on table "public"."team_member" from "service_role";


